export const ICONS = {
  home: require('./images/home.png'),
  bookmark: require('./images/bookmark.png'),
  pet: require('./images/pet.png'),
  setting: require('./images/setting.png'),
  cat: require('./images/logo.png'),
  keyboardArrowRight: require('./images/keyboard_arrow_right.png'),
  keyboardArrowLeft: require('./images/keyboard_arrow_left.png'),
  add: require('./images/add.png'),
  sport: require('./images/sport.png'),
  food: require('./images/food.png'),
  arrowRight: require('./images/arrow_right.png'),
  male: require('./images/male.png'),
  female: require('./images/female.png'),
  create: require('./images/create.png'),
  expandMore: require('./images/expand_more.png'),
  perm_media: require('components/MFC-Icon/images/perm_media.png'),
};
